Fix failing toolchain resolution (#15)
`bazel test //...` was failing with
```
ERROR: While resolving toolchains for target //tests:library: no
matching toolchains found for types //rules:toolchain_type
ERROR: Analysis of target '//tests:library' failed; build aborted: no
matching toolchains found for types //rules:toolchain_type
```

For some reason it cannot be registered from macro.
I'll need to get back to this and cleanup toolchain/runtime setup